apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-letsencrypt
  namespace: prod
spec:
  dnsNames:
    - 2023.blue.com
  issuerRef:
    name: prod-letsencrypt
    kind: ClusterIssuer