apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: damsaji168@gmail.com
    privateKeySecretRef:
      name: prod-letsencrypt
    solvers:
      - http01:
           ingress:
              class: nginx